exports.bluetooth = require('./modules/bluetooth.js')
exports.fileSystem = require('./modules/fs.js')
exports.monitor = require('./modules/monitor.js')
exports.network = require('./modules/network.js')
exports.notif = require('./modules/notif.js')
exports.shortcut = require('./modules/shortcut.js')
exports.socketClient = require('./modules/SocketClient.js')
exports.sound = require('./modules/sound.js')
exports.task = require('./modules/tasks.js')
exports.database = require('./modules/database.js')
exports.auth = require('./modules/auth.js')
//exports.time = require('./modules/time.js')

console.log('[CORE] Welcome on graviton')